CREATE TABLE IF NOT EXISTS public.simulation_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    simulation_attempt boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.simulation_users ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.user_profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email varchar(255) NOT NULL,
    name varchar(100) NOT NULL,
    phone varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.user_profiles;
CREATE POLICY "Users can insert their own profile"
    ON public.user_profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    INSERT INTO public.user_profiles (id, email, name, phone)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data ->> 'name', ''),
        COALESCE(NEW.raw_user_meta_data ->> 'phone', '')
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DROP POLICY IF EXISTS "Users can view their own profile" ON public.user_profiles;
CREATE POLICY "Users can view their own profile"
    ON public.user_profiles FOR SELECT
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.user_profiles;
CREATE POLICY "Users can update their own profile"
    ON public.user_profiles FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- Backfill profiles for accounts created before the trigger was installed.
INSERT INTO public.user_profiles (id, email, name, phone)
SELECT
    id,
    email,
    COALESCE(raw_user_meta_data ->> 'name', ''),
    COALESCE(raw_user_meta_data ->> 'phone', '')
FROM auth.users
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    phone = EXCLUDED.phone;

-- Run this query in Supabase SQL Editor to view submitted simulation inputs.
SELECT id, name, simulation_attempt, created_at
FROM public.simulation_users
ORDER BY created_at DESC;

-- View registered account details. Passwords are never stored in this table.
SELECT id, email, name, phone, created_at
FROM public.user_profiles
ORDER BY created_at DESC;

-- View Auth users together with their plain-text profile phone number.
-- Run this query in the Supabase SQL Editor.
SELECT
    u.id,
    u.email,
    p.name,
    p.phone,
    u.created_at
FROM auth.users AS u
LEFT JOIN public.user_profiles AS p
    ON p.id = u.id
ORDER BY u.created_at DESC;
